export const ADD_ARCHIVED = "ADD_ARCHIVED";
export const ARCHIVE_BUDGET = "ARCHIVE_BUDGET";
export const DELETE_ARCHIVED = "DELETE_ARCHIVED";

export const ADD_BUDGETS = "ADD_BUDGETS";
export const SELECT_BUDGET = "SELECT_BUDGET";
export const REMOVE_BUDGET = "REMOVE_BUDGET";
export const CHANGE_BUDGET = "CHANGE_BUDGET";
export const ADD_BUDGET = "ADD_BUDGET";
export const MAKE_BACKUP = "MAKE_BACKUP";
export const CLEAR_BACKUP = "CLEAR_BACKUP";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const ADD_EXPENDITURES = "ADD_EXPENDITURES";
export const REMOVE_EXPENDITURE = "REMOVE_EXPENDITURE";
export const REMOVE_BUDGET_EXPENDITURES = "REMOVE_BUDGET_EXPENDITURES";
export const UPDATE_EXPENDITURE = "UPDATE_EXPENDITURE";
export const ADD_EXPENDITURE = "ADD_EXPENDITURE";

export const SET_SETTINGS = "SET_SETTINGS";

export const CHANGE_VIEW = "CHANGE_VIEW";

export const SET_TOOLTIP = "SET_TOOLTIP";
export const CLEAR_TOOLTIP = "CLEAR_TOOLTIP";
